[tox]
env_list = py311, py312, py313, lint, type
requires = tox-uv

[testenv]
runner = uv-venv-lock-runner
dependency_groups = dev
extras = httpx, aiohttp
commands = pytest {posargs}

[testenv:lint]
commands =
    ruff check src tests scripts
    ruff format --check src tests scripts

[testenv:type]
commands = mypy src
