from uex.models.base import Model, ResultMeta
from uex.models.categories import Category, CategoryAttribute
from uex.models.commodities import (
    Commodity,
    CommodityAlert,
    CommodityAverage,
    CommodityPrice,
    CommodityPriceHistory,
    CommodityPriceSummary,
    CommodityRanking,
    CommodityRawAverage,
    CommodityRawPrice,
    CommodityRawPriceSummary,
    CommodityRoute,
    CommodityStatus,
)
from uex.models.crew import CrewMember
from uex.models.currencies import CurrencyIndex, CurrencyIndexSnapshot
from uex.models.data import DataInfo, DataMonitorEntry, DataParameters
from uex.models.fuel import FuelPrice, FuelPriceSummary
from uex.models.game_version import GameVersionEntry, GameVersions
from uex.models.items import Item, ItemAttribute, ItemPrice, ItemPriceSummary
from uex.models.marketplace import (
    MarketplaceAverage,
    MarketplaceAverageSummary,
    MarketplaceFavorite,
    MarketplaceListing,
    MarketplaceNegotiation,
    MarketplaceNegotiationMessage,
    MarketplacePriceAverage,
    MarketplacePriceAverageSummary,
    MarketplacePriceHistory,
    MarketplaceTrend,
)
from uex.models.misc import ReleaseNote
from uex.models.polls import Poll, PollAuditEntry
from uex.models.refineries import RefineryAudit, RefineryCapacity, RefineryMethod, RefineryYield
from uex.models.terminals import Terminal, TerminalDistance
from uex.models.universe import (
    City,
    Company,
    Contact,
    Contract,
    Faction,
    JumpPoint,
    Jurisdiction,
    Moon,
    Orbit,
    OrbitDistance,
    Outpost,
    Planet,
    PointOfInterest,
    SpaceStation,
    StarSystem,
)
from uex.models.user import (
    FleetVehicle,
    Organization,
    User,
    UserNotification,
    UserRefineryJob,
    UserTrade,
    WalletBalance,
)
from uex.models.vehicles import (
    Vehicle,
    VehicleLoaner,
    VehiclePrice,
    VehiclePurchasePrice,
    VehiclePurchasePriceSummary,
    VehicleRentalPrice,
    VehicleRentalPriceSummary,
)

MODELS: dict[str, type[Model]] = {
    "Category": Category,
    "CategoryAttribute": CategoryAttribute,
    "City": City,
    "Commodity": Commodity,
    "CommodityAlert": CommodityAlert,
    "CommodityAverage": CommodityAverage,
    "CommodityPrice": CommodityPrice,
    "CommodityPriceHistory": CommodityPriceHistory,
    "CommodityPriceSummary": CommodityPriceSummary,
    "CommodityRanking": CommodityRanking,
    "CommodityRawAverage": CommodityRawAverage,
    "CommodityRawPrice": CommodityRawPrice,
    "CommodityRawPriceSummary": CommodityRawPriceSummary,
    "CommodityRoute": CommodityRoute,
    "CommodityStatus": CommodityStatus,
    "Company": Company,
    "Contact": Contact,
    "Contract": Contract,
    "CrewMember": CrewMember,
    "CurrencyIndex": CurrencyIndex,
    "CurrencyIndexSnapshot": CurrencyIndexSnapshot,
    "DataInfo": DataInfo,
    "DataMonitorEntry": DataMonitorEntry,
    "DataParameters": DataParameters,
    "Faction": Faction,
    "FleetVehicle": FleetVehicle,
    "FuelPrice": FuelPrice,
    "FuelPriceSummary": FuelPriceSummary,
    "GameVersionEntry": GameVersionEntry,
    "GameVersions": GameVersions,
    "Item": Item,
    "ItemAttribute": ItemAttribute,
    "ItemPrice": ItemPrice,
    "ItemPriceSummary": ItemPriceSummary,
    "JumpPoint": JumpPoint,
    "Jurisdiction": Jurisdiction,
    "MarketplaceAverage": MarketplaceAverage,
    "MarketplaceAverageSummary": MarketplaceAverageSummary,
    "MarketplaceFavorite": MarketplaceFavorite,
    "MarketplaceListing": MarketplaceListing,
    "MarketplaceNegotiation": MarketplaceNegotiation,
    "MarketplaceNegotiationMessage": MarketplaceNegotiationMessage,
    "MarketplacePriceAverage": MarketplacePriceAverage,
    "MarketplacePriceAverageSummary": MarketplacePriceAverageSummary,
    "MarketplacePriceHistory": MarketplacePriceHistory,
    "MarketplaceTrend": MarketplaceTrend,
    "Moon": Moon,
    "Orbit": Orbit,
    "OrbitDistance": OrbitDistance,
    "Organization": Organization,
    "Outpost": Outpost,
    "Planet": Planet,
    "PointOfInterest": PointOfInterest,
    "Poll": Poll,
    "PollAuditEntry": PollAuditEntry,
    "RefineryAudit": RefineryAudit,
    "RefineryCapacity": RefineryCapacity,
    "RefineryMethod": RefineryMethod,
    "RefineryYield": RefineryYield,
    "ReleaseNote": ReleaseNote,
    "SpaceStation": SpaceStation,
    "StarSystem": StarSystem,
    "Terminal": Terminal,
    "TerminalDistance": TerminalDistance,
    "User": User,
    "UserNotification": UserNotification,
    "UserRefineryJob": UserRefineryJob,
    "UserTrade": UserTrade,
    "Vehicle": Vehicle,
    "VehicleLoaner": VehicleLoaner,
    "VehiclePrice": VehiclePrice,
    "VehiclePurchasePrice": VehiclePurchasePrice,
    "VehiclePurchasePriceSummary": VehiclePurchasePriceSummary,
    "VehicleRentalPrice": VehicleRentalPrice,
    "VehicleRentalPriceSummary": VehicleRentalPriceSummary,
    "WalletBalance": WalletBalance,
}

__all__ = [
    "MODELS",
    "Category",
    "CategoryAttribute",
    "City",
    "Commodity",
    "CommodityAlert",
    "CommodityAverage",
    "CommodityPrice",
    "CommodityPriceHistory",
    "CommodityPriceSummary",
    "CommodityRanking",
    "CommodityRawAverage",
    "CommodityRawPrice",
    "CommodityRawPriceSummary",
    "CommodityRoute",
    "CommodityStatus",
    "Company",
    "Contact",
    "Contract",
    "CrewMember",
    "CurrencyIndex",
    "CurrencyIndexSnapshot",
    "DataInfo",
    "DataMonitorEntry",
    "DataParameters",
    "Faction",
    "FleetVehicle",
    "FuelPrice",
    "FuelPriceSummary",
    "GameVersionEntry",
    "GameVersions",
    "Item",
    "ItemAttribute",
    "ItemPrice",
    "ItemPriceSummary",
    "JumpPoint",
    "Jurisdiction",
    "MarketplaceAverage",
    "MarketplaceAverageSummary",
    "MarketplaceFavorite",
    "MarketplaceListing",
    "MarketplaceNegotiation",
    "MarketplaceNegotiationMessage",
    "MarketplacePriceAverage",
    "MarketplacePriceAverageSummary",
    "MarketplacePriceHistory",
    "MarketplaceTrend",
    "Model",
    "Moon",
    "Orbit",
    "OrbitDistance",
    "Organization",
    "Outpost",
    "Planet",
    "PointOfInterest",
    "Poll",
    "PollAuditEntry",
    "RefineryAudit",
    "RefineryCapacity",
    "RefineryMethod",
    "RefineryYield",
    "ReleaseNote",
    "ResultMeta",
    "SpaceStation",
    "StarSystem",
    "Terminal",
    "TerminalDistance",
    "User",
    "UserNotification",
    "UserRefineryJob",
    "UserTrade",
    "Vehicle",
    "VehicleLoaner",
    "VehiclePrice",
    "VehiclePurchasePrice",
    "VehiclePurchasePriceSummary",
    "VehicleRentalPrice",
    "VehicleRentalPriceSummary",
    "WalletBalance",
]
